### ISSUE TITLE
[FE] Issue Tracker List page UI

### ISSUE THREAD

**Issue by jthw1005** [juolly/issue-tracker#7]
### 🐳 Progress
- [x] #18
- [ ] nav 및 register 버튼 컴포넌트🐭
- [x] #16
  - [ ] issue-list container🐹
  - [ ] issue-list header🐰
  - [x] #17
